BEGIN TRANSACTION;

DROP TABLE IF EXISTS [__EFMigrationsHistory];
DROP TABLE IF EXISTS [Report];
DROP TABLE IF EXISTS [DesignCategory];
DROP TABLE IF EXISTS [AccessibilityCategory];
DROP TABLE IF EXISTS [DesignIssue];
DROP TABLE IF EXISTS [AccessibilityIssue];
DROP TABLE IF EXISTS [FontLegibility];
DROP TABLE IF EXISTS [UserFeedbacks];

COMMIT;
