INSERT INTO [DesignCategory] (Name, Description, ScanMethod)
    VALUES
    ('Visual Hierarchy', 'The arrangement of UI elements in a way that guides users’ attention based on importance. Key Factors: Size, color, contrast, spacing, and placement. Example: A bold, large headline at the top, followed by supporting text in smaller font.', 'Custom'),
    ('Broken Links', 'Links that no longer work, leading to 404 errors or dead pages. Impact: Frustrates users and harms SEO rankings.', 'Custom'),
    ('Mobile Responsiveness', 'The ability of a website to adapt to different screen sizes (phones, tablets, desktops). Impact: Essential for usability and search ranking (Google prioritizes mobile-friendly sites).', 'Custom'),
    ('Favicon', 'A small icon representing a website, displayed in browser tabs and bookmarks. Impact: Enhances branding, credibility, and user recognition. Solution: Use a 16x16 or 32x32px favicon and add <link rel="icon" href="favicon.ico"> to your HTML.', 'Custom'),
    ('Font Legibility', 'How easy it is to read text on a screen, based on font, font size, weight, spacing, and contrast. Impact: Poor readability leads to user frustration and increased bounce rates Solution: Use clear sans-serif fonts like Roboto or Open Sans and maintain good contrast.', 'Custom'),
    ('Color Scheme', 'The combination of colors used across a website for branding and readability. Impact: Affects emotions, usability, and aesthetics. Solution: Use a primary, secondary, and accent color, ensuring accessibility with sufficient contrast.', 'Custom'),
    ('Text Structure', 'How text is formatted, including headings, paragraphs, and bullet points. Impact: Improves readability, scanability, and SEO. Solution: Use short paragraphs, clear headings (H1-H3), and ample spacing.', 'Custom'),
    ('Number of Fonts', 'The total fonts used in a web design. Too many fonts create inconsistency and clutter. Impact: Affects brand consistency and readability. Solution: Stick to 2-3 fonts max—one for headings, one for body text, and an optional accent font.', 'Custom'),
    ('Symmetry', 'The balance of elements in a design, either symmetrical (mirrored) or asymmetrical (intentionally off-balance). Impact: Creates harmony and structure, making layouts feel polished. Solution: Use grid-based layouts to maintain alignment.', 'Custom'),
    ('Animations', 'Motion effects like fade-ins, scroll effects, hover interactions, or page transitions. Impact: Can enhance engagement but should not slow performance. Solution: Use subtle, purposeful animations, avoiding excessive motion that distracts.', 'Custom'),
    ('Pop Ups', 'Windows or overlays that appear dynamically on a webpage, often for promotions or alerts. Impact: Can boost conversions but annoy users if too aggressive. Solution: Make pop-ups easy to dismiss and use them sparingly.', 'Custom'),
    ('Audio', 'Sounds played on a website, including background music, alerts, or voice instructions. Impact: Can enhance user experience but should never play automatically without control. Solution: Allow users to mute, pause, or adjust volume.', 'Custom'),
    ('User Feedback', 'Visual or interactive responses to user actions, like hover effects, loading indicators, or confirmation messages. Impact: Helps users understand system status and feel in control. Solution: Implement toast notifications, progress bars, and real-time validation.', 'Custom'),
    ('Number of scrolls', 'The total scrolling required to view content. Long pages should be easy to navigate. Impact: Too much scrolling can reduce engagement if key info is buried. Solution: Use sticky navigation, back-to-top buttons, and collapsible sections.', 'Custom'),
    ('Performance', 'The speed and responsiveness of a website, including load times and smooth interactions. Impact: Affects SEO, user retention, and conversion rates. Solution: Optimize images, reduce HTTP requests, use caching, and leverage CDNs.', 'Custom'),
    ('F Pattern', 'A common eye-tracking pattern where users scan horizontally first, then vertically. Impact: The top-left area of a page gets the most attention. Solution: Place key content (headlines, CTAs) in the top-left area.', 'Custom'),
    ('Z Pattern', 'A common eye-tracking pattern where users scan in a “Z” shape (left to right, then diagonally down). Impact: Ideal for landing pages and visual storytelling. Solution: Arrange CTA buttons and key information along the “Z” path', 'Custom');

